flowchart LR
  L0["Level 0<br/>Prep"] --> L1["Level 1<br/>Fundamentals"]
  L1 --> L2["Level 2<br/>Distributed"]
  L2 --> L3["Level 3<br/>Advanced"]
  L2 -.-> L4["Level 4<br/>Tech guides"]
  L3 -.-> L4
  L1 -.-> L5["Level 5<br/>OS / HW"]
